name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run: git clone --depth 1 https://github.com/sstephenson/bats.git
    - name: Run tests
      run: PATH="./bats/bin:$PATH" bats --version; PATH="./bats/bin:$PATH" ./run-tests.sh
      # run: PATH="./bats/bin:$PATH" make test
